### ISSUE TITLE
Support for flutter_map 7.0.0

### ISSUE THREAD

**Issue by ARASHz4** [ibrierley/flutter_map_dragmarker#45]
Not compatible with flutter_map v7.0.0

**Comment by PHKenny** [comment]
You can add this in your `pubspec.yaml` to temporally support the latest changes in this library, supported in flutter_map 7.0.0 (I 
tested)

```
dependency_overrides:
  flutter_map_dragmarker:
    git:
      url: https://github.com/ibrierley/flutter_map_dragmarker
      ref: master # You can change this reference to a specific commit if you want to prevent unwanted upgrades
```

Of course that isn't a production solution, but for temporal use until the library reaches the latest version with flutter_map 7 support.
